(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np

ini_array = np.array([1, 2, 3, 6, 4, 5])

res = np.flip(ini_array)

print(res)

[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods


In [11]:
import numpy as np

arr = np.array([[1,2,3], [2,4,5],[1,2,3]])

res = arr.flatten()

print( res )



[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


In [2]:
import numpy as np

an_array = np.array([[1, 3], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])

comparison = an_array == another_array
# print(comparison)#individual

final = comparison.all()
print(final) #as a whole

False


(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np

# x = np.array([1,2,3,4,5,1,2,1,1,1])
# max0 = np.bincount(x).argmax()
# print(max0)

y = np.array([1,1,1,2,3,4,2,4,3,3])
max1 = np.bincount(y)
maxim= np.max(max1)

for i in range(len(max1)):
    if max1[i] == maxim:
        print(i, " ")

[0 3 2 3 2]
1  
3  


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise


In [ ]:
import numpy as np

yea = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total = yea.sum()
print(total)

total = yea.sum(axis = 1)
print(total)

total = yea.sum(axis = 0)
print(total)



45
[[14]
 [16]
 [15]] 

[[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix


In [3]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

trace = np.trace(n_array)
print(trace)

w, v = np.linalg.eig(n_array)
print(w)

print(v)

print(np.linalg.inv(n_array))

print(np.linalg.det(n_array))


176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [16]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]

print("After multiplication->\n",np.matmul(p,q))

After multiplication->
 [[16 19]
 [26 31]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [17]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("Inner product ->\n",np.inner(x,y))
print("Outer product ->\n",np.outer(x,y))
print("Cross product ->\n",np.cross(x,y))

Inner product ->
 [[17 52]
 [13 62]]
Outer product ->
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cross product ->
 [[-20   4   7]
 [-84  36  20]]


***Q2: Based on NumPy Mathematics and Statistics***

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row


---



In [18]:
array = np.array([[1, -2, 3],[-4, 5, -6]])

print("Absolute values ->",np.absolute(array))

percentiles = np.percentile(array, [25, 50, 75], axis = 0)
print("Percentiles -> ",percentiles)

print("Mean ->\n",np.mean(array))
print("Median ->\n",np.median(array))
print("Standard Deviation ->\n",np.std(array))



Absolute values -> [[1 2 3]
 [4 5 6]]
Percentiles ->  [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Mean ->
 -0.5
Median ->
 -0.5
Standard Deviation ->
 3.8622100754188224


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [12]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("Floor ->",np.floor(a))
print("Ceiling ->",np.ceil(a))
print("Truncated ->",np.trunc(a))
print("Rounded ->",np.round(a))

Floor -> [-2. -2. -1.  0.  1.  1.  3.]
Ceiling -> [-1. -1. -0.  1.  2.  2.  3.]
Truncated -> [-1. -1. -0.  0.  1.  1.  3.]
Rounded -> [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements


In [22]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

print("Sorted array ->",np.sort(array))

print("Indices of sorted array ->",np.argsort(array))

print("4 smallest elements ->",np.sort(array)[:4])

print("5 largest elements ->",np.sort(array)[-5:])


Sorted array -> [ 10  16  16  52  54  62 453]
[ 10  52  62  16  16  54 453]
Indices of sorted array -> [0 3 4 1 5 2 6]
4 smallest elements -> [10 16 16 52]
5 largest elements -> [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only

In [23]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

print("Integer elements only ->",array[array == array.astype(int)])

print("Float elements only ->",array[array != array.astype(int)])

Integer elements only -> [1. 2. 3. 2.]
Float elements only -> [1.2 2.2]


Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)


In [24]:

from PIL import Image
import numpy as np

def img_to_array(path):
  img = Image.open(path)
  if img.mode == 'RGB':
    arr = np.array(img)
    with open('rgb_image.txt', 'w') as f:
      for row in arr:
        np.savetxt(f, row, fmt='%d')
  elif img.mode == 'L':
    arr = np.array(img)
    with open('grey_scale_image.txt', 'w') as f:
      np.savetxt(f, arr, fmt='%d')
  else:
    print('Image mode not supported.')
